### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by qingchenkanlu** [edwardnguyen1705/robotic-grasping-faster-rcnn#1]
Hi，the structure of vgg16 maybe need to be changed,the source file
class vgg16(_fasterRCNN):
     def init(self, classes, pretrained=False, class_agnostic=False):
     self.model_path = 'data/pretrained_model/vgg16_caffe.pth'
     self.dout_base_model = 512
     self.pretrained = pretrained
     self.class_agnostic = class_agnostic
but yours in predict.py
self.fasterRCNN = vgg16(self.grasp_classes,
self.grasp_poses,
pretrained=False,
class_agnostic=self.class_agnostic,)
is there any mistake?Thanks

**Comment by edwardnguyen1705** [comment]
Hi, you are right. I made some commits before, but changes what I made do not get updated. Sorry for that. 
I have just made an update.

**Comment by qingchenkanlu** [comment]
OK，thanks！
